### ISSUE TITLE
export bookmark not generating json file

### ISSUE THREAD

**Issue by aligit** [jonschoning/espial-docker#1]
Dear @jonschoning 
Thank you for the great product.

**Problem**: Want to export bookmarks but doesn't seem to generate a json file. I used the following command:

> docker-compose exec espial ./migration exportbookmarks --conn /app/data/espial.sqlite3 --userName userteta --bookmarkFile export.json

**Expected**: expect.json

**Got**: no file

Thanks in advance

**Comment by jonschoning** [comment]
you need to prefix your bookmarkFile path with `/app/data/` to get it to export into external docker volume (your host filesystem) instead of exporting inside the docker image. so 
```
docker-compose exec espial ./migration exportbookmarks --conn /app/data/espial.sqlite3 --userName userteta --bookmarkFile /app/data/export.json
```
